spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: teamtrackdb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true


jwt:
  secret:
    api:
      key: ${JWT_SECRET_KEY}
